---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
  - PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.2.2"
  - PUPPET_GEM_VERSION="~> 4.2.3"
  - PUPPET_GEM_VERSION="~> 4.3.0"
  - PUPPET_GEM_VERSION="~> 4.3.1"
matrix:
  include:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes"
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes" 
    - rvm: 2.1
      env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" 
    - rvm: 2.1
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" 
    - rvm: 2.2
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" 
    - rvm: 2.3.1
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" 
    - rvm: 2.3.1
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" 
