---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  include:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes"
    - rvm: 2.1
      env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" 
    - rvm: 2.1
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" 
    - rvm: 2.2
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" 
    - rvm: 2.3.1
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" 
    - rvm: 2.3.1
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" 
